### ISSUE TITLE
History is broken when mutating nested state

### ISSUE THREAD

**Issue by arnoson** [wobsoriano/pinia-undo#1]
When having nested state like this:
```js
state: {
  nested: {
    value: 0
  }
}
```
and then updating the nested state in the store:
```js
state.nested.value = 10
```
This will also alter the history, since `undo-stacker` is returning a reference to the current stack entry in it's update function.

Returning a copy in `undo-stacker` would fix this:
```js
  function update() {
    current = JSON.parse(JSON.stringify(stack[index - 1]))

    state = {
      first: index === 1,
      last: index === stack.length,
      current,
    }

    return current
  }
```

If you wan't to I can create a PR, but since this is such a small change I thought it might be easier to just create and issue.

**Comment by wobsoriano** [comment]
Thanks! Fixed
