### ISSUE TITLE
Not working with Vue 2 anymore

### ISSUE THREAD

**Issue by T-Zahil** [wobsoriano/pinia-undo#2]
Hey 👋,

Thanks a lot for your work!

I just want to let you know that the recent changes you made break this plugin with Vue2, because `markRaw` is only available in Vue3.
Not sure if this is intentional or not, as it is still written in the Readme that it's compatible with Vue2.

`markRaw` is available in `vue-demi` though 😄

**Comment by wobsoriano** [comment]
Oops, my bad. I was testing something yesterday and forgot to remove it. Thanks! 😄
