### ISSUE TITLE
Could this library not use stringify()?

### ISSUE THREAD

**Issue by npiccolotto** [wobsoriano/pinia-undo#4]
Hello,

after some digging I realized that the stack holds stringified versions of the state. This is fine for data that is basically JSON. I'm less sure about, e.g., instances of classes:

```js
class Meal {
  constructor(food, portion) {
    this.food = food;
    this.portion = portion;
  }
  eat() {
    this.portion = 0;
  }
}
const dinner = new Meal('potato', 6);
```

I didn't find a quick way to try it out, but I assume that safe-stringifying `dinner` and `JSON.parse()`ing it again yields just an object with `food` and `portion` keys, i.e., there wouldn't be an `eat()` function to call anymore. I assume similar issues arise with other structures, like recursive references, `Map`s, typed arrays...? Also, storing data as strings is quite inefficient.

So, further assuming that you agree that this warrants improvement, do you have thoughts on how this could be implemented?

**Comment by wobsoriano** [comment]
Not using stringify anymore.
