### ISSUE TITLE
How to use with Nuxt 3 with pinia module?

### ISSUE THREAD

**Issue by ernstov** [wobsoriano/pinia-undo#7]
https://nuxt.com/modules/pinia

**Comment by wobsoriano** [comment]
You just need to create a plugin:

```ts
import { PiniaUndo } from 'pinia-undo'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$pinia.use(PiniaUndo);
});
```

**Comment by ernstov** [comment]
@wobsoriano  yes I tried it but getting error

```
index.js:20 Uncaught (in promise) DOMException: Failed to execute 'structuredClone' on 'Window': function wrap() {
        var args = new Array(arguments.length);
        for (var i = 0; i < args.length; i++)...<omitted>... } could not be cloned.
        at
         http://localhost:3000/_nuxt/@fs/C:/Users/ernst/Desktop/wrk/project/node_modules/.cache/vite/client/deps/pinia-undo.js?t=1689097924498&v=8e10c8d7:209:115
```

**Comment by wobsoriano** [comment]
Can you try making it a client plugin?

**Comment by ernstov** [comment]
yes also tried with client only plugin, and also with 

const pinia = usePinia() 

and in app.vue mounted `pinia.use`

**Comment by wobsoriano** [comment]
Mind creating a basic repro via stackblitz or send a repo link here instead? So I can play with it

**Comment by paullindquist** [comment]
Here is a basic repo. I get the error: `Uncaught TypeError: counterStore.undo is not a function`

https://github.com/paullindquist/nuxt_pinia_undo

**Comment by wobsoriano** [comment]
@paullindquist  You should install a pinia plugin inside a Nuxt plugin instead:

```ts
// plugins/pinia.client.ts
import { PiniaUndo } from "pinia-undo";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.$pinia.use(PiniaUndo);
});
```

**Comment by paullindquist** [comment]
I was pretty sure I had tried this, but must have had something wrong. This works! Thanks!!
