### ISSUE TITLE
Not working with Pinia Setup Store?

### ISSUE THREAD

**Issue by andyjamesn** [wobsoriano/pinia-undo#8]
I am referring to this page on Pinia which refers to a syntax to setup a store using refs and computed instead of getters and actions

[https://pinia.vuejs.org/core-concepts/#setup-stores](https://pinia.vuejs.org/core-concepts/#setup-stores)

When I try use this I get this error

`Failed to execute 'structuredClone' on 'Window': () => traverse(baseGetter()) could not be cloned.`

Does this plugin only work with Pinia's option store setup?

**Comment by wobsoriano** [comment]
Hi, please try again and feel free to open if you encounter the same issue :)
